import type { EditorThemeClasses } from 'lexical';

import styles from './EditorTheme.module.css';

const theme: EditorThemeClasses = {
  characterLimit: styles['PlaygroundEditorTheme__characterLimit'],
  code: styles['PlaygroundEditorTheme__code'],
  codeHighlight: {
    atrule: styles['PlaygroundEditorTheme__tokenAttr'],
    attr: styles['PlaygroundEditorTheme__tokenAttr'],
    boolean: styles['PlaygroundEditorTheme__tokenProperty'],
    builtin: styles['PlaygroundEditorTheme__tokenSelector'],
    cdata: styles['PlaygroundEditorTheme__tokenComment'],
    char: styles['PlaygroundEditorTheme__tokenSelector'],
    class: styles['PlaygroundEditorTheme__tokenFunction'],
    'class-name': styles['PlaygroundEditorTheme__tokenFunction'],
    comment: styles['PlaygroundEditorTheme__tokenComment'],
    constant: styles['PlaygroundEditorTheme__tokenProperty'],
    deleted: styles['PlaygroundEditorTheme__tokenProperty'],
    doctype: styles['PlaygroundEditorTheme__tokenComment'],
    entity: styles['PlaygroundEditorTheme__tokenOperator'],
    function: styles['PlaygroundEditorTheme__tokenFunction'],
    important: styles['PlaygroundEditorTheme__tokenVariable'],
    inserted: styles['PlaygroundEditorTheme__tokenSelector'],
    keyword: styles['PlaygroundEditorTheme__tokenAttr'],
    namespace: styles['PlaygroundEditorTheme__tokenVariable'],
    number: styles['PlaygroundEditorTheme__tokenProperty'],
    operator: styles['PlaygroundEditorTheme__tokenOperator'],
    prolog: styles['PlaygroundEditorTheme__tokenComment'],
    property: styles['PlaygroundEditorTheme__tokenProperty'],
    punctuation: styles['PlaygroundEditorTheme__tokenPunctuation'],
    regex: styles['PlaygroundEditorTheme__tokenVariable'],
    selector: styles['PlaygroundEditorTheme__tokenSelector'],
    string: styles['PlaygroundEditorTheme__tokenSelector'],
    symbol: styles['PlaygroundEditorTheme__tokenProperty'],
    tag: styles['PlaygroundEditorTheme__tokenProperty'],
    url: styles['PlaygroundEditorTheme__tokenOperator'],
    variable: styles['PlaygroundEditorTheme__tokenVariable'],
  },
  embedBlock: {
    base: styles['PlaygroundEditorTheme__embedBlock'],
    focus: styles['PlaygroundEditorTheme__embedBlockFocus'],
  },
  hashtag: styles['PlaygroundEditorTheme__hashtag'],
  heading: {
    h1: 'text-2xl font-semibold',
    h2: 'text-xl font-semibold',
    h3: 'text-lg font-semibold',
    // h4: styles['PlaygroundEditorTheme__h4'],
    // h5: styles['PlaygroundEditorTheme__h5'],
    // h6: styles['PlaygroundEditorTheme__h6'],
  },
  image: styles['editor-image'],
  link: styles['PlaygroundEditorTheme__link'],
  list: {
    // listitem: 'PlaygroundEditorTheme__listItem',
    // listitemChecked: 'PlaygroundEditorTheme__listItemChecked',
    // listitemUnchecked: 'PlaygroundEditorTheme__listItemUnchecked',
    nested: {
      listitem: styles['PlaygroundEditorTheme__nestedListItem'],
    },
    // olDepth: [
    //   'PlaygroundEditorTheme__ol1',
    //   'PlaygroundEditorTheme__ol2',
    //   'PlaygroundEditorTheme__ol3',
    //   'PlaygroundEditorTheme__ol4',
    //   'PlaygroundEditorTheme__ol5',
    // ],
    ul: 'ml-6 list-disc',
    ol: 'ml-6 list-decimal',
  },
  ltr: styles['PlaygroundEditorTheme__ltr'],
  mark: styles['PlaygroundEditorTheme__mark'],
  markOverlap: styles['PlaygroundEditorTheme__markOverlap'],
  paragraph: 'my-3',
  quote: styles['PlaygroundEditorTheme__quote'],
  rtl: styles['PlaygroundEditorTheme__rtl'],
  text: {
    bold: 'font-semibold',
    code: 'p-0.25 bg-gray-100 border border-gray-200 rounded dark:bg-gray-800 dark:border-gray-700',
    italic: 'italic',
    strikethrough: 'line-through',
    underline: 'underline',
    underlineStrikethrough: 'underline-strikethrough',
  },
};

export default theme;
