name: cypress tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'

    - uses: supabase/setup-cli@v1.1.1
    - run: supabase start

    - name: Cypress run
      uses: cypress-io/github-action@v4.2.0
      with:
        build: npm run build
        start: npm start
